name: Hourly Job

on:
  schedule:
    - cron: '0 * * * 1-5'   

  workflow_dispatch:  # optional manual trigger


jobs:
  run-hourly-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Adjust to your required Python version

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt # If you have a requirements file

      - name: Run the script
        env:
          sender_email: ${{ secrets.EMAIL_USER }}
          sender_password: ${{ secrets.EMAIL_PASS }}
        run: python "Mail stock 1h.py"

